%% build_sinc3_simulink.m
% 构建 sinc^3 NPLC 数字滤波器 Simulink 模型
% Buffer(M) → MATLAB Function (sinc3_frame) → 输出
% 模拟 DMM 工频抑制: 0.5V DC + 50/100/150Hz 干扰 + 噪声

clear; close all; clc;

%% --- 参数 ---
fs = 2e6;          % ADC 采样率 2 MHz
f_line = 50;       % 工频 50 Hz
nplc = 1;          % NPLC = 1
M = round(nplc * fs / f_line);  % M = 40000
Ts = 1/fs;         % 采样周期 0.5 us
T_sim = 0.5;       % 仿真时长 0.5 s

fprintf('fs=%.0fHz, M=%d, ODR=%.2fHz, T_sim=%.2fs\n', fs, M, fs/M, T_sim);

%% --- 创建模型 ---
model = 'sinc3_nplc_simulink';
if bdIsLoaded(model), close_system(model, 0); end
if exist([model '.slx'], 'file'), delete([model '.slx']); end
new_system(model);
open_system(model);

set_param(model, 'StopTime', num2str(T_sim));
set_param(model, 'Solver', 'FixedStepDiscrete');
set_param(model, 'FixedStep', num2str(Ts));

%% ========== 1. 信号源 ==========
% 真实被测信号: DC 0.5V + 3Hz 波动
add_block('simulink/Sources/Constant',  [model '/DC'], ...
    'Position', [30, 320, 80, 350], 'Value', '0.5', 'SampleTime', num2str(Ts));
add_block('simulink/Sources/Sine Wave', [model '/3Hz'], ...
    'Position', [30, 270, 80, 300], ...
    'Amplitude', '0.05', 'Frequency', '2*pi*3', 'SampleTime', num2str(Ts));
add_block('simulink/Math Operations/Add', [model '/TrueSig'], ...
    'Position', [130, 280, 180, 330], 'Inputs', '++');
add_line(model, 'DC/1', 'TrueSig/1');
add_line(model, '3Hz/1', 'TrueSig/2');

% 干扰: 50 + 100 + 150 Hz + 噪声
add_block('simulink/Sources/Sine Wave',  [model '/F50'], ...
    'Position', [30, 50, 80, 80], ...
    'Amplitude', '1.0', 'Frequency', '2*pi*50', 'SampleTime', num2str(Ts));
add_block('simulink/Sources/Sine Wave',  [model '/F100'], ...
    'Position', [30, 100, 80, 130], ...
    'Amplitude', '0.3', 'Frequency', '2*pi*100', 'SampleTime', num2str(Ts));
add_block('simulink/Sources/Sine Wave',  [model '/F150'], ...
    'Position', [30, 150, 80, 180], ...
    'Amplitude', '0.1', 'Frequency', '2*pi*150', 'SampleTime', num2str(Ts));
add_block('simulink/Sources/Random Number', [model '/Noise'], ...
    'Position', [30, 200, 80, 230], ...
    'Variance', '0.0004', 'SampleTime', num2str(Ts));

% 求和
add_block('simulink/Math Operations/Add', [model '/SumNoise'], ...
    'Position', [140, 80, 190, 150], 'Inputs', '+++');
add_line(model, 'F50/1',  'SumNoise/1');
add_line(model, 'F100/1', 'SumNoise/2');
add_line(model, 'F150/1', 'SumNoise/3');

add_block('simulink/Math Operations/Add', [model '/SumAll'], ...
    'Position', [240, 100, 290, 170], 'Inputs', '+++');
add_line(model, 'TrueSig/1', 'SumAll/1');
add_line(model, 'SumNoise/1','SumAll/2');
add_line(model, 'Noise/1',   'SumAll/3');

% 24-bit 量化
add_block('simulink/Discontinuities/Quantizer', [model '/Quant'], ...
    'Position', [340, 100, 390, 150], 'QuantizationInterval', '2/2^24');
add_line(model, 'SumAll/1', 'Quant/1');

%% ========== 2. Buffer + MATLAB Function 滤波器 ==========
% Buffer: 每 M 个采样组装成一帧
add_block('dspbuff3/Buffer', [model '/Buffer'], ...
    'Position', [440, 100, 500, 160], ...
    'N', num2str(M), 'V', '0', 'ic', '0');
add_line(model, 'Quant/1', 'Buffer/1');

% MATLAB Function: 对一帧 M 个采样做 3 级 MA, 取最后一点 (= 抽取)
% 用 Interpreted MATLAB Function 调用 sinc3_frame_filter.m
add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
    [model '/Filter'], ...
    'Position', [560, 100, 640, 170], ...
    'MATLABFcn', 'sinc3_frame_filter', ...
    'OutputDimensions', '1');
add_line(model, 'Buffer/1', 'Filter/1');

%% ========== 3. 创建 sinc3_frame_filter.m ==========
ffn = 'D:\matlab_filter_test\sinc3_frame_filter.m';
if ~exist(ffn, 'file')
    fid = fopen(ffn, 'w');
    fprintf(fid, '%s', [...
        'function y = sinc3_frame_filter(u)\n', ...
        '%% Sinc^3 filter for one frame of M samples.\n', ...
        '%% u = Mx1 vector -> y = scalar (last point after 3 MA stages)\n', ...
        'M = length(u);\n', ...
        'v = u(:);\n', ...
        '%% Stage 1\n', ...
        'cs = cumsum([zeros(M,1); v]);\n', ...
        's1 = (cs(M+1:end) - cs(1:end-M)) / M;\n', ...
        '%% Stage 2\n', ...
        'cs = cumsum([zeros(M,1); s1]);\n', ...
        's2 = (cs(M+1:end) - cs(1:end-M)) / M;\n', ...
        '%% Stage 3\n', ...
        'cs = cumsum([zeros(M,1); s2]);\n', ...
        's3 = (cs(M+1:end) - cs(1:end-M)) / M;\n', ...
        'y = s3(end);\n', ...
        'end\n']);
    fclose(fid);
    fprintf('Created: sinc3_frame_filter.m\n');
end

%% ========== 4. To Workspace + Scope ==========
add_block('simulink/Sinks/To Workspace', [model '/T_Filt'], ...
    'Position', [690, 110, 750, 150], ...
    'VariableName', 'sim_filtered', 'SaveFormat', 'Array');
add_line(model, 'Filter/1', 'T_Filt/1');

add_block('simulink/Sinks/To Workspace', [model '/T_ADC'], ...
    'Position', [440, 40, 500, 80], ...
    'VariableName', 'sim_adc', 'SaveFormat', 'Array');
add_line(model, 'Quant/1', 'T_ADC/1');

add_block('simulink/Sinks/To Workspace', [model '/T_True'], ...
    'Position', [240, 230, 300, 270], ...
    'VariableName', 'sim_true', 'SaveFormat', 'Array');
add_line(model, 'TrueSig/1', 'T_True/1');

% Scope: 2行1列
add_block('simulink/Sinks/Scope', [model '/Scope'], ...
    'Position', [700, 250, 900, 480], ...
    'NumInputPorts', '2', 'LayoutDimensionsString', '[2,1]');

% Mux 合路上轴: ADC输入 + 真实信号
add_block('simulink/Signal Routing/Mux', [model '/Mux'], ...
    'Position', [500, 280, 530, 315], 'Inputs', '2');
add_line(model, 'Quant/1', 'Mux/1');
add_line(model, 'TrueSig/1', 'Mux/2');
add_line(model, 'Mux/1', 'Scope/1');

% 下轴: 滤波输出
add_line(model, 'Filter/1', 'Scope/2');

%% ========== 5. 保存 ==========
save_system(model);
fprintf('Model saved: %s.slx\n', model);
fprintf('Run: sim(''%s'');\n', model);
